### ISSUE TITLE
xcodebuild  -project WeWorkMacPlugin.xcodeproj -scheme WeWorkMacPlugin -configuration Release  -destination 'platform=OS X,arch=x86_64' DSTROOT="" archive xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance make: *** [build-wework] Error 1

### ISSUE THREAD

**Issue by hxxiaolong** [wangliangliang2/WeWorkMacPlugin#5]
mac电脑报这个错
xcodebuild  -project WeWorkMacPlugin.xcodeproj -scheme WeWorkMacPlugin -configuration Release  -destination 'platform=OS X,arch=x86_64' DSTROOT="" archive
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build-wework] Error 1

我电脑是写在了xcode  我同事电脑xcode没动过，同样的错误

**Comment by wangliangliang2** [comment]
需要切换到xcode
xcode-select --switch /Applications/Xcode.app/Contents/Developer/
